# LAB 01.01 - Practice submission

In [12]:
!wget --no-cache -O init.py -q https://raw.githubusercontent.com/fagonzalezo/ai4eng-unal/main/content/init.py
import init; init.init(force_download=False); init.get_weblink()


In [13]:
import inspect
from local.lib.rlxmoocapi import session
session.LoginSequence(endpoint=init.endpoint, course_id=init.course_id, lab_id="L01.01", varname="student");

logging in as mamayaro@unal.edu.co... please wait
you are not registered for any session in this course. login failed!!

-------------
LOGIN FAILED!!!
-------------


### Ejercicio 1: Suma dos matrices

Completa la función `suma_matrices` para que, dadas dos arrays numpy cualquiera devuelva la suma elemento a elemento.

#### Ejemplo de ejecución

    > s = np.array([1,2,3])
    > t = np.array([4,5,6])
    > suma_matrices(s,t)
    
      [5 7 9]
     
_Sugerencia_: completa el código de la siguiente manera:

    def suma_matrices(a,b):
       ## --- TU CODIGO AQUI ---
       result = a + b
       return result

In [4]:

def suma_matrices(a,b):
    ## --- TU CODIGO AQUI ---
    result = np.add(a,b)
    return result



comprueba manualmente tu código

In [5]:
import numpy as np
a = np.random.randint(10, size=(3,2))
b = np.random.randint(10, size=(3,2))
print (a)
print (b)
print (suma_matrices(a,b))

[[2 3]
 [7 7]
 [6 5]]
[[6 3]
 [5 4]
 [7 7]]
[[ 8  6]
 [12 11]
 [13 12]]


#### registra tu solución en línea

In [14]:
student.submit_task(globals(), task_id="task_01");

AttributeError: 'NoneType' object has no attribute 'submit_task'

### Ejercicio 2: Realiza un cálculo

En este ejercicio, al ejecutar la celda de más abajo, se generará una lista de número aleatorios.

Tendrás que calcular el valor promedio de la lista y asignarlo a la variable `avg` más abajo.

Puedes usar el método que quieras para realizar el cálculo (a mano, excel, python, etc.) lo que importa es el valor que obtengas.


In [24]:
import numpy as np
rlist = np.random.randint(100, size=10)
rlist

array([ 8, 12, 57, 90, 59, 33, 18, 26, 12, 20])

#### tu solución

In [25]:
avg = np.mean(rlist)
print(avg)

33.5


#### registra tu solución en línea

In [ ]:
student.submit_task(globals(), task_id="task_02");